// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yamgumiyaicqrfkzlwke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhbWd1bWl5YWljcXJma3psd2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzE4MzIsImV4cCI6MjA1NDM0NzgzMn0.v-AvIuov96BH_Zms-KJrf0cR2kr4jNc37Nru0OYGQts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
